on:
  pull_request:
  push:
    branches:
      - main
name: Tests
env:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-version: ['8.1']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-version }}'
          tools: composer:v2

      - name: Get build directory
        id: build_cache
        run: echo "::set-output name=dir::build/"

      - name: Cache build directory
        uses: actions/cache@v3
        with:
          path: ${{ steps.build_cache.outputs.dir }}
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.json') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --optimize-autoloader --no-progress

      - name: Run tests
        run: vendor/bin/phpunit tests/
